/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SpotRouteImport } from './routes/spot'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaccineResultRunIdRouteImport } from './routes/vaccine-result.$runId'
import { Route as ResultCheckIdRouteImport } from './routes/result.$checkId'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotRoute = SpotRouteImport.update({
  id: '/spot',
  path: '/spot',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccineResultRunIdRoute = VaccineResultRunIdRouteImport.update({
  id: '/vaccine-result/$runId',
  path: '/vaccine-result/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultCheckIdRoute = ResultCheckIdRouteImport.update({
  id: '/result/$checkId',
  path: '/result/$checkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/research': typeof ResearchRoute
  '/spot': typeof SpotRoute
  '/workshop': typeof WorkshopRoute
  '/result/$checkId': typeof ResultCheckIdRoute
  '/vaccine-result/$runId': typeof VaccineResultRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/research': typeof ResearchRoute
  '/spot': typeof SpotRoute
  '/workshop': typeof WorkshopRoute
  '/result/$checkId': typeof ResultCheckIdRoute
  '/vaccine-result/$runId': typeof VaccineResultRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/research': typeof ResearchRoute
  '/spot': typeof SpotRoute
  '/workshop': typeof WorkshopRoute
  '/result/$checkId': typeof ResultCheckIdRoute
  '/vaccine-result/$runId': typeof VaccineResultRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/research'
    | '/spot'
    | '/workshop'
    | '/result/$checkId'
    | '/vaccine-result/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/research'
    | '/spot'
    | '/workshop'
    | '/result/$checkId'
    | '/vaccine-result/$runId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/research'
    | '/spot'
    | '/workshop'
    | '/result/$checkId'
    | '/vaccine-result/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ResearchRoute: typeof ResearchRoute
  SpotRoute: typeof SpotRoute
  WorkshopRoute: typeof WorkshopRoute
  ResultCheckIdRoute: typeof ResultCheckIdRoute
  VaccineResultRunIdRoute: typeof VaccineResultRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot': {
      id: '/spot'
      path: '/spot'
      fullPath: '/spot'
      preLoaderRoute: typeof SpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccine-result/$runId': {
      id: '/vaccine-result/$runId'
      path: '/vaccine-result/$runId'
      fullPath: '/vaccine-result/$runId'
      preLoaderRoute: typeof VaccineResultRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$checkId': {
      id: '/result/$checkId'
      path: '/result/$checkId'
      fullPath: '/result/$checkId'
      preLoaderRoute: typeof ResultCheckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ResearchRoute: ResearchRoute,
  SpotRoute: SpotRoute,
  WorkshopRoute: WorkshopRoute,
  ResultCheckIdRoute: ResultCheckIdRoute,
  VaccineResultRunIdRoute: VaccineResultRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
